backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://takeshape.netlify.com/

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: "Heading", name: "heading", widget: "string" }