backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

display_url: https://takeshape.netlify.com/

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - { label: "Meta Description", name: "pageDescription", widget: "string" }
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Copy", name: "copy", widget: "string" }
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - { label: "Meta Description", name: "pageDescription", widget: "string" }